In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2996, 9908, 3452, 8229],
 [2996, 9908, 3452, 2114],
 [2996, 14, 3452, 8978],
 [7802, 7626, 9657, 4019, 7707],
 [7802, 7626, 9657, 4019, 2181],
 [4314, 2996, 1672, 3452, 4087],
 [1487, 3545, 2347, 4019]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2996 9908 3452 8229]
 [   0    0    0    0 2996 9908 3452 2114]
 [   0    0    0    0 2996   14 3452 8978]
 [   0    0    0 7802 7626 9657 4019 7707]
 [   0    0    0 7802 7626 9657 4019 2181]
 [   0    0    0 4314 2996 1672 3452 4087]
 [   0    0    0    0 1487 3545 2347 4019]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 56ms/step


array([[[ 4.8140895e-02,  1.9451413e-02,  3.4888361e-02,  4.7363531e-02,
          1.5129451e-02,  4.7950353e-02, -8.3791241e-03, -3.1015290e-02,
         -4.4058692e-02, -4.1665684e-02],
        [ 4.8140895e-02,  1.9451413e-02,  3.4888361e-02,  4.7363531e-02,
          1.5129451e-02,  4.7950353e-02, -8.3791241e-03, -3.1015290e-02,
         -4.4058692e-02, -4.1665684e-02],
        [ 4.8140895e-02,  1.9451413e-02,  3.4888361e-02,  4.7363531e-02,
          1.5129451e-02,  4.7950353e-02, -8.3791241e-03, -3.1015290e-02,
         -4.4058692e-02, -4.1665684e-02],
        [ 4.8140895e-02,  1.9451413e-02,  3.4888361e-02,  4.7363531e-02,
          1.5129451e-02,  4.7950353e-02, -8.3791241e-03, -3.1015290e-02,
         -4.4058692e-02, -4.1665684e-02],
        [ 1.1348117e-02,  4.1734722e-02,  4.9528252e-02, -4.9857248e-02,
         -3.6223877e-02,  1.1397712e-03, -3.1516932e-02, -1.8216480e-02,
         -2.9645432e-02,  4.1632924e-02],
        [-3.8940907e-03,  3.8955573e-02, -1.5714847e-02, -3.

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2996, 9908, 3452, 8229], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 21ms/step


array([[ 0.04814089,  0.01945141,  0.03488836,  0.04736353,  0.01512945,
         0.04795035, -0.00837912, -0.03101529, -0.04405869, -0.04166568],
       [ 0.04814089,  0.01945141,  0.03488836,  0.04736353,  0.01512945,
         0.04795035, -0.00837912, -0.03101529, -0.04405869, -0.04166568],
       [ 0.04814089,  0.01945141,  0.03488836,  0.04736353,  0.01512945,
         0.04795035, -0.00837912, -0.03101529, -0.04405869, -0.04166568],
       [ 0.04814089,  0.01945141,  0.03488836,  0.04736353,  0.01512945,
         0.04795035, -0.00837912, -0.03101529, -0.04405869, -0.04166568],
       [ 0.01134812,  0.04173472,  0.04952825, -0.04985725, -0.03622388,
         0.00113977, -0.03151693, -0.01821648, -0.02964543,  0.04163292],
       [-0.00389409,  0.03895557, -0.01571485, -0.03741624,  0.00181323,
         0.04685335, -0.01008334,  0.04548078,  0.0096946 ,  0.02570423],
       [-0.02606036,  0.03636828, -0.04433424, -0.00168984, -0.00764928,
         0.04153529,  0.00486239,  0.02257974